// for Login in Security Admin
export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

//Sign out
export const SIGN_OUT = "SIGN_OUT";

//Refresh Token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

//Clear Message
export const CLEARE_MESSAGE = "CLEARE_MESSAGE";
// for save Bank User
export const SAVE_BANK_USER_INIT = "SAVE_BANK_USER_INIT";
export const SAVE_BANK_USER_SUCCESS = "SAVE_BANK_USER_SUCCESS";
export const SAVE_BANK_USER_FAIL = "SAVE_BANK_USER_FAIL";

// for save Corporate User
export const SAVE_CORPORATE_USER_INIT = "SAVE_CORPORATE_USER_INIT";
export const SAVE_CORPORATE_USER_SUCCESS = "SAVE_CORPORATE_USER_SUCCESS";
export const SAVE_CORPORATE_USER_FAIL = "SAVE_CORPORATE_USER_FAIL";

// for get new Bank User Requests
export const GET_NEW_BANK_USER_REQUESTS_INIT =
  "GET_NEW_BANK_USER_REQUESTS_INIT";
export const GET_NEW_BANK_USER_REQUESTS_SUCCESS =
  "GET_NEW_BANK_USER_REQUESTS_SUCCESS";
export const GET_NEW_BANK_USER_REQUESTS_FAIL =
  "GET_NEW_BANK_USER_REQUESTS_FAIL";

// for get new CORPORATE User Requests
export const GET_NEW_CORPORATE_USER_REQUESTS_INIT =
  "GET_NEW_CORPORATE_USER_REQUESTS_INIT";
export const GET_NEW_CORPORATE_USER_REQUESTS_SUCCESS =
  "GET_NEW_CORPORATE_USER_REQUESTS_SUCCESS";
export const GET_NEW_CORPORATE_USER_REQUESTS_FAIL =
  "GET_NEW_CORPORATE_USER_REQUESTS_FAIL";

// For Reject User Request
export const REJECT_USER_REQUEST_INIT = "REJECT_USER_REQUEST_INIT";
export const REJECT_USER_REQUEST_SUCCESS = "REJECT_USER_REQUEST_SUCCESS";
export const REJECT_USER_REQUEST_FAIL = "REJECT_USER_REQUEST_FAIL";

//For Get All Users List
export const GET_ALL_USERS_LIST_INIT = "GET_ALL_USERS_LIST_INIT";
export const GET_ALL_USERS_LIST_SUCCESS = "GET_ALL_USERS_LIST_SUCCESS";
export const GET_ALL_USERS_LIST_FAIL = "GET_ALL_USERS_LIST_FAIL";

//Send Email For Reset Password
export const SEND_EMAIL_RESET_PASSWORD_INIT = "SEND_EMAIL_RESET_PASSWORD_INIT";
export const SEND_EMAIL_RESET_PASSWORD_SUCCESS =
  "SEND_EMAIL_RESET_PASSWORD_SUCCESS";
export const SEND_EMAIL_RESET_PASSWORD_FAIL = "SEND_EMAIL_RESET_PASSWORD_FAIL";

//Search Corporate Users
export const SEARCH_CORPORATE_USERS_INIT = "SEARCH_CORPORATE_USERS_INIT";
export const SEARCH_CORPORATE_USERS_SUCCESS = "SEARCH_CORPORATE_USERS_SUCCESS";
export const SEARCH_CORPORATE_USERS_FAIL = "SEARCH_CORPORATE_USERS_FAIL";

//Search Bank Users
export const SEARCH_BANK_USERS_INIT = "SEARCH_BANK_USERS_INIT";
export const SEARCH_BANK_USERS_SUCCESS = "SEARCH_BANK_USERS_SUCCESS";
export const SEARCH_BANK_USERS_FAIL = "SEARCH_BANK_USERS_FAIL";

//GetAllUserStatus reducer
export const GET_ALL_USER_STATUS_INIT = "GET_ALL_USER_STATUS_INIT";
export const GET_ALL_USER_STATUS_SUCCESS = "GET_ALL_USER_STATUS_SUCCESS";
export const GET_ALL_USER_STATUS_FAIL = "GET_ALL_USER_STATUS_FAIL";

//Get All ROLES LIST
export const ROLE_LIST_INIT = "ROLE_LIST_INIT";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";

//Get All User ROLES LIST
export const GET_BANK_USER_ROLES_INIT = "GET_BANK_USER_ROLES_INIT";
export const GET_BANK_USER_ROLES_SUCCESS = "GET_BANK_USER_ROLES_SUCCESS";
export const GET_BANK_USER_ROLES_FAIL = "GET_BANK_USER_ROLES_FAIL";

//Update Bank User
export const UPDATE_BANK_USER_INIT = "UPDATE_BANK_USER_INIT";
export const UPDATE_BANK_USER_SUCCESS = "UPDATE_BANK_USER_SUCCESS";
export const UPDATE_BANK_USER_FAIL = "UPDATE_BANK_USER_FAIL";

//Update Corporate User
export const UPDATE_CORPORATE_USER_INIT = "UPDATE_CORPORATE_USER_INIT";
export const UPDATE_CORPORATE_USER_SUCCESS = "UPDATE_CORPORATE_USER_SUCCESS";
export const UPDATE_CORPORATE_USER_FAIL = "UPDATE_CORPORATE_USER_FAIL";

//Get All Branches
export const GET_ALL_BRANCHES_INIT = "GET_ALL_BRANCHES_INIT";
export const GET_ALL_BRANCHES_SUCCESS = "GET_ALL_BRANCHES_SUCCESS";
export const GET_ALL_BRANCHES_FAIL = "GET_ALL_BRANCHES_FAIL";

// Confirmation Modal
export const CONFIRMATION_MODAL = "CONFIRMATION_MODAL";

//Get User Settings
export const GET_USER_SETTINGS_INIT = "GET_USER_SETTINGS_INIT";
export const GET_USER_SETTINGS_SUCCESS = "GET_USER_SETTINGS_SUCCESS";
export const GET_USER_SETTINGS_FAIL = "GET_USER_SETTINGS_FAIL";

//Update user Settings
export const UPDATE_USER_SETTINGS_INIT = "UPDATE_USER_SETTINGS_INIT";
export const UPDATE_USER_SETTINGS_SUCCESS = "UPDATE_USER_SETTINGS_SUCCESS";
export const UPDATE_USER_SETTINGS_FAIL = "UPDATE_USER_SETTINGS_FAIL";

//Get Market Time Settings
export const GET_MARKET_TIME_SETTINGS_INIT = "GET_MARKET_TIME_SETTINGS_INIT";
export const GET_MARKET_TIME_SETTINGS_SUCCESS =
  "GET_MARKET_TIME_SETTINGS_SUCCESS";
export const GET_MARKET_TIME_SETTINGS_FAIL = "GET_MARKET_TIME_SETTINGS_FAIL";

//Save Market Time Settings

export const SAVE_MARKET_TIME_SETTINGS_INIT = "SAVE_MARKET_TIME_SETTINGS_INIT";
export const SAVE_MARKET_TIME_SETTINGS_SECCESS =
  "SAVE_MARKET_TIME_SETTINGS_SECCESS";
export const SAVE_MARKET_TIME_SETTINGS_FAIL = "SAVE_MARKET_TIME_SETTINGS_FAIL";

//Logout
export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
