// for Login in Security Admin
export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

//Sign out
export const SIGN_OUT = "SIGN_OUT";

// for save Bank User
export const SAVE_BANK_USER_INIT = "SAVE_BANK_USER_INIT";
export const SAVE_BANK_USER_SUCCESS = "SAVE_BANK_USER_SUCCESS";
export const SAVE_BANK_USER_FAIL = "SAVE_BANK_USER_FAIL";

// for save Corporate User
export const SAVE_CORPORATE_USER_INIT = "SAVE_CORPORATE_USER_INIT";
export const SAVE_CORPORATE_USER_SUCCESS = "SAVE_CORPORATE_USER_SUCCESS";
export const SAVE_CORPORATE_USER_FAIL = "SAVE_CORPORATE_USER_FAIL";

// for get new Bank User Requests
export const GET_NEW_BANK_USER_REQUESTS_INIT =
  "GET_NEW_BANK_USER_REQUESTS_INIT";
export const GET_NEW_BANK_USER_REQUESTS_SUCCESS =
  "GET_NEW_BANK_USER_REQUESTS_SUCCESS";
export const GET_NEW_BANK_USER_REQUESTS_FAIL =
  "GET_NEW_BANK_USER_REQUESTS_FAIL";

// for get new CORPORATE User Requests
export const GET_NEW_CORPORATE_USER_REQUESTS_INIT =
  "GET_NEW_CORPORATE_USER_REQUESTS_INIT";
export const GET_NEW_CORPORATE_USER_REQUESTS_SUCCESS =
  "GET_NEW_CORPORATE_USER_REQUESTS_SUCCESS";
export const GET_NEW_CORPORATE_USER_REQUESTS_FAIL =
  "GET_NEW_CORPORATE_USER_REQUESTS_FAIL";

// For Reject User Request
export const REJECT_USER_REQUEST_INIT = "REJECT_USER_REQUEST_INIT";
export const REJECT_USER_REQUEST_SUCCESS = "REJECT_USER_REQUEST_SUCCESS";
export const REJECT_USER_REQUEST_FAIL = "REJECT_USER_REQUEST_FAIL";

//Send Email For Reset Password
export const SEND_EMAIL_RESET_PASSWORD_INIT = "SEND_EMAIL_RESET_PASSWORD_INIT";
export const SEND_EMAIL_RESET_PASSWORD_SUCCESS =
  "SEND_EMAIL_RESET_PASSWORD_SUCCESS";
export const SEND_EMAIL_RESET_PASSWORD_FAIL = "SEND_EMAIL_RESET_PASSWORD_FAIL";
